<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Product>Swagger Merge SDK</Product>
    <Description>
      Swagger Merge SDK to process the merging of multiple Swagger files into a single Swagger file.
      This is useful for bringing together the API layer of a distributed service architecture where you wish to expose the APIs via a single API gateway.
    </Description>
    <PackageTags>Swagger Merge API Documentation OpenAPI SDK</PackageTags>
    <RootNamespace>SwaggerMerge</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.301" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="17.1.0" />
  </ItemGroup>

</Project>
