name: CI - SDK

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - src/SwaggerMerge.SDK/**
      - build/GetBuildVersion.psm1
      - .github/workflows/ci-sdk.yml
      - Directory.Build.props
  pull_request:
    branches:
      - main
    paths:
      - src/SwaggerMerge.SDK/**
      - build/GetBuildVersion.psm1
      - .github/workflows/ci-sdk.yml
      - Directory.Build.props
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    env:
      BUILD_CONFIG: "Release"
      PROJECT: "./src/SwaggerMerge.SDK/SwaggerMerge.SDK.csproj"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Build Version
        run: |
          Import-Module .\build\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT }}

      - name: Build SDK
        run: dotnet build ${{ env.PROJECT }} --configuration ${{ env.BUILD_CONFIG }} -p:Version=${{ env.BUILD_VERSION }} --no-restore

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'windows-latest'
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{ secrets.NUGET_API_KEY }}
