name: CI - SDK

on:
  push:
    branches:
      - main
    paths:
      - src/SwaggerMerge.SDK/**
      - build/GetBuildVersion.psm1
      - .github/workflows/ci-sdk.yml
      - Directory.Build.props
  pull_request:
    branches:
      - main
    paths:
      - src/SwaggerMerge.SDK/**
      - build/GetBuildVersion.psm1
      - .github/workflows/ci-sdk.yml
      - Directory.Build.props
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        version: [net6.0, net7.0, net8.0]

    env:
      BUILD_CONFIG: "Release"
      PROJECT: "./src/SwaggerMerge.SDK/SwaggerMerge.SDK.csproj"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Build Version
        run: |
          Import-Module .\build\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore $SOLUTION

      - name: Build SDK
        run: dotnet build $PROJECT /p:Configuration=$env:BUILD_CONFIG /p:Platform="Any CPU" /p:Version=$BUILD_VERSION

      # - name: Publish
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
